import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Simple blue square with "MCP" text as base64 PNG
// This is a minimal valid PNG that will work as a placeholder
const icon16 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwQAADsEBuJFr7QAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC4zjOaXUAAAAGNJREFUOE+lU0EKACAIy/7/6XYQFBWdtpsDgWyOhlprjJBa66Cx1kqttTJaay0zpmkCY4y01gIzz7OMMaK1loQQwDknIQS89xJCkBDCBu89OedkjJExRt57KaVkrZVSiogIP3wBQ2kgGqu2lWsAAAAASUVORK5CYII=', 'base64');

const icon32 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwQAADsEBuJFr7QAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC4zjOaXUAAAAJNJREFUWEftl0EKwCAMBPv/p7eCICo2JrO7FHqYQ0HI7GyMRdM0zTAMU5IkaK01pmnSIUmSnPN2HMdtjDF67/UYYwznHLz3OI4DpZS9lJIy55zs+x7neUZQSnGMMYRS6koI4VVrrTfWWmuttcYY01tr0VqLUsoldI7jCCHE8ziOKOfcL6XUIoRYhBBrjDFERP+NAMRXMIJr0nXbAAAAAElFTkSuQmCC', 'base64');

const icon48 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwQAADsEBuJFr7QAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC4zjOaXUAAAALJJREFUaEPtmEEKwCAMBPP/p/eCIIpWk+xuC/UwhxYhszMxFkIIIYQQQgj5B03TzMMwLEmSYJqmLUkS5Jy34ziuY4xRe++xLMs8juOSc46UUlJK3UIIl1prrbXWnHOO9x7OOWutrbVWGGPQWotSyq1zRkop7Ps+HscR53neI4TgGGN4hRBeWmvtjbXWImstjDEwxqC1FqWUS0oppZTijPnknKOUUksIsbYQYhMRERERX8MA8ZNiohhn7G8AAAAASUVORK5CYII=', 'base64');

const icon128 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwQAADsEBuJFr7QAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC4zjOaXUAAAAVJJREFUeF7t1rENACAMA0H2382hQEJCRPa7gqJw5e7MzLkAaAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFAFYAYAUAVgBgBQBWAGAFADZz5wUAAAAAAAAAAAAA4K8BYsQEqixm7d4AAAAASUVORK5CYII=', 'base64');

// Write the icon files
fs.writeFileSync(path.join(__dirname, 'icon-16.png'), icon16);
fs.writeFileSync(path.join(__dirname, 'icon-32.png'), icon32);
fs.writeFileSync(path.join(__dirname, 'icon-48.png'), icon48);
fs.writeFileSync(path.join(__dirname, 'icon-128.png'), icon128);

console.log('✅ Icon files created successfully!');
console.log('Icons saved in:', __dirname);